---
version: '3.8'
services:

  prd-bazarr-app:
    image: docker-registry.theautomation.nl/coen/prd-bazarr-app:latest
    container_name: prd-bazarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 6767:6767
    networks:
      - transmission-openvpn
    volumes:
      - ./config/bazarr:/config
      - movies:/movies
      - series:/tv

  prd-radarr-app:
    image: docker-registry.theautomation.nl/coen/prd-radarr-app:latest
    container_name: prd-radarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 7878:7878
    networks:
      - transmission-openvpn
      - node-red
    volumes:
      - ./config/radarr:/config
      - completed:/data/completed
      - movies:/movies

  prd-sonarr-app:
    image: docker-registry.theautomation.nl/coen/prd-sonarr-app:latest
    container_name: prd-sonarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 8989:8989
    networks:
      - transmission-openvpn
      - node-red
    volumes:
      - ./config/sonarr:/config
      - completed:/data/completed
      - series:/tv

  prd-prowlarr-app:
    image: docker-registry.theautomation.nl/coen/prd-prowlarr-app:latest
    container_name: prd-prowlarr-app
    restart: unless-stopped
    env_file: prd-prowlarr-app.env
    ports:
      - 9117:9117
    networks:
      - transmission-openvpn
    volumes:
      - ./config/prowlarr:/config

networks:
  transmission-openvpn:
    name: transmission-openvpn
  node-red:
    name: node-red

volumes:
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=storage-server.lan,nolock,soft,rw,nfsvers=4"
      device: ":/r10_8tb/downloads/media/movies"
  series:
    driver_opts:
      type: "nfs"
      o: "addr=storage-server.lan,nolock,soft,rw,nfsvers=4"
      device: ":/r10_8tb/downloads/media/series"
  completed:
    driver_opts:
      type: "nfs"
      o: "addr=storage-server.lan,nolock,soft,rw,nfsvers=4"
      device: ":/r10_8tb/downloads/media/completed"