---
version: '3.8'
services:

  prd-bazarr-app:
    image: docker-registry.theautomation.nl/coen/prd-bazarr-app:latest
    container_name: prd-bazarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 6767:6767
    networks:
      home-services:
    volumes:
      - ./config/bazarr:/config
      - /mnt/slow-storage/temp/downloads/media/movies:/movies
      - /mnt/slow-storage/temp/downloads/media/series:/tv

  prd-radarr-app:
    image: docker-registry.theautomation.nl/coen/prd-radarr-app:latest
    container_name: prd-radarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 7878:7878
    networks:
      home-services:
    volumes:
      - ./config/radarr:/config
      - /mnt/slow-storage/temp/downloads/media/completed:/data/completed
      - /mnt/slow-storage/temp/downloads/media/movies:/movies

  prd-sonarr-app:
    image: docker-registry.theautomation.nl/coen/prd-sonarr-app:latest
    container_name: prd-sonarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    ports:
      - 8989:8989
    networks:
      home-services:
    volumes:
      - ./config/sonarr:/config
      - /mnt/slow-storage/temp/downloads/media/completed:/data/completed
      - /mnt/slow-storage/temp/downloads/media/series:/tv

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16
