---
version: '3.8'
services:

  prd-bazarr-app:
    image: docker-registry.theautomation.nl/coen/prd-bazarr-app:latest
    container_name: prd-bazarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    networks:
      - reverse-proxy
    volumes:
      - ./config/bazarr:/config
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/movies:/movies
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/series:/tv

  prd-radarr-app:
    image: docker-registry.theautomation.nl/coen/prd-radarr-app:latest
    container_name: prd-radarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    networks:
      - reverse-proxy
      - transmission-openvpn
      - node-red
    volumes:
      - ./config/radarr:/config
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/completed:/data/completed
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/movies:/movies

  prd-sonarr-app:
    image: docker-registry.theautomation.nl/coen/prd-sonarr-app:latest
    container_name: prd-sonarr-app
    restart: unless-stopped
    env_file: prd-bazarr-app.env
    networks:
      - reverse-proxy
      - transmission-openvpn
      - node-red
    volumes:
      - ./config/sonarr:/config
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/completed:/data/completed
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/series:/tv

  prd-jackett-app:
    image: docker-registry.theautomation.nl/coen/prd-jackett-app:latest
    container_name: prd-jackett-app
    restart: unless-stopped
    env_file: prd-jackett-app.env
    networks:
      - reverse-proxy
    volumes:
      - ./config/jackett:/config
      - /mnt/R10_S8TB_C120GB/temp/downloads/media/jackett:/downloads

networks:
  transmission-openvpn:
    name: transmission-openvpn
  reverse-proxy:
    name: reverse-proxy
  node-red:
    name: node-red
