---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-entertainment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/media-entertainment.git
    targetRevision: main
    path: deploy/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
