apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arrs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/arrs.git
    targetRevision: HEAD
    path: k8s/manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
